name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  debug-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"
