name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
        - name: Print GitHub Context
          run: echo "${{ toJson(github) }}"

  lint_js:
      name: Lint JavaScript Files
      runs-on: ubuntu-latest
      steps:
        - name: Print GitHub Context
          run: echo "${{ toJson(github) }}"
