name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      run: echo "${{ toJson(github) }}"
    
    - name: Set up Python
      run: echo "${{ toJson(github) }}"

    - name: Install dependencies
      run: echo "${{ toJson(github) }}"
      
    - name: Print working directory
      run: echo "${{ toJson(github) }}"

    - name: Run Linter
      run: echo "${{ toJson(github) }}"

  lint_js:
      name: Lint JavaScript Files
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        run: echo "${{ toJson(github) }}"

      - name: Install Node.js
        run: echo "${{ toJson(github) }}"

      - name: Install JSHint
        run: echo "${{ toJson(github) }}"

      - name: Run Linter
        run: echo "${{ toJson(github) }}"
